
import java.awt.Desktop;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Classe para implementação do CRUD no jFrame Form. Atividade avaliativa
 * @author GUIlherme Bezerra
 * @since 30/11/2024 18:00h
 */
public class FrmCadastro extends javax.swing.JFrame {
    private int count = 14;
    DefaultTableModel model;
    Connection conexao;
    PreparedStatement pst;
    ResultSet rs;
    //float result;
    
    /**
     * Creates new form FrmCadastro
     */
    public FrmCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInserir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtEstoqueMin = new javax.swing.JTextField();
        txtEstoqueMax = new javax.swing.JTextField();
        txtFatorLucro = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        txtNcm = new javax.swing.JTextField();
        txtCodBarras = new javax.swing.JTextField();
        txtPesquisar = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btInserir.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btInserir.setContentAreaFilled(false);
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 120, 260, 70));

        btAlterar.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btAlterar.setContentAreaFilled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 230, 260, 70));

        btDeletar.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btDeletar.setContentAreaFilled(false);
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 260, 70));

        btLimpar.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 460, 260, 70));

        btPesquisar.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 570, 260, 70));

        btSair.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        btSair.setContentAreaFilled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 260, 70));

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 332, 925, 60));

        cbStatus.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"A - Ativo", "I - Inativo"}));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 125, 249, 44));

        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 128, 358, 38));

        txtData.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 128, 230, 38));

        txtNome.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 234, 525, 37));

        txtEstoque.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtEstoque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 234, 363, 37));

        txtEstoqueMin.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtEstoqueMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtEstoqueMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 451, 247, 38));

        txtEstoqueMax.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtEstoqueMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtEstoqueMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 451, 245, 38));

        txtFatorLucro.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtFatorLucro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtFatorLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 644, 180, 30));

        txtPrecoCompra.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtPrecoCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoCompraFocusLost(evt);
            }
        });
        txtPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoCompraActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 550, 200, 40));

        txtPrecoVenda.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtPrecoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoVendaFocusLost(evt);
            }
        });
        getContentPane().add(txtPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 549, 192, 38));

        txtNcm.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtNcm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 640, 246, 38));

        txtCodBarras.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtCodBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 736, 561, 34));

        txtPesquisar.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtPesquisar.setText("Pesquisar por...");
        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusLost(evt);
            }
        });
        txtPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPesquisarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPesquisarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPesquisarMouseReleased(evt);
            }
        });
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 726, 259, 40));

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 0, 51));
        txtID.setText("ID = ");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 80, -1));

        tblProdutos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Status", "Nome", "Qtd Estoque", "Qtd Mín", "Qtd Máx", "Preço Compra", "Preço Venda", "Fator %"
            }
        ));
        tblProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblProdutosFocusGained(evt);
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblProdutosMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, 1270, 230));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTitulo.setText("SISTEMA | CADASTRO DE PRODUTOS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("imagem para ID.png ou ID.jpg e movê-la para a pastaDoProjeto/src/imagens");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 707, 440, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Se quiser adicionar ou mudar a imagem do produto basta renomear a");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 693, -1, -1));
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 466, 284, 227));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEG\\Documents\\CodeRepository\\Privado\\JavaProjects\\ProjFinal\\ProjetoFinal.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        cadastrar();
    }//GEN-LAST:event_btInserirActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        listar();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        excluir(txtCodigo.getText());
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        update();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        limpar();
        selecionar();
    }//GEN-LAST:event_tblProdutosMouseClicked

    // Quando FatorLucro perder o foco
    private void txtPrecoCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoCompraFocusLost
        if (!txtPrecoCompra.getText().equals("") && !txtPrecoVenda.getText().equals("")) {
            float aux = (Float.parseFloat(txtPrecoCompra.getText())/100) * Float.parseFloat(txtPrecoVenda.getText());
            if (Float.parseFloat(txtPrecoVenda.getText()) < Float.parseFloat(txtPrecoCompra.getText()))
                aux = aux * -1; 
            txtFatorLucro.setText(String.valueOf(aux));
        }
        else txtFatorLucro.setText("");
    }//GEN-LAST:event_txtPrecoCompraFocusLost

    // Quando FatorLucro perder o foco
    private void txtPrecoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoVendaFocusLost
        if (!txtPrecoCompra.getText().equals("") && !txtPrecoVenda.getText().equals("")) {
            float aux = (Float.parseFloat(txtPrecoCompra.getText())/100) * Float.parseFloat(txtPrecoVenda.getText());
            if (Float.parseFloat(txtPrecoVenda.getText()) < Float.parseFloat(txtPrecoCompra.getText()))
                aux = aux * -1; 
            txtFatorLucro.setText(String.valueOf(aux));
        }
        else txtFatorLucro.setText("");
    }//GEN-LAST:event_txtPrecoVendaFocusLost

    private void tblProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseExited
        
    }//GEN-LAST:event_tblProdutosMouseExited

    private void tblProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblProdutosFocusGained
        
    }//GEN-LAST:event_tblProdutosFocusGained

    private void txtPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCompraActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusGained
        
    }//GEN-LAST:event_txtPesquisarFocusGained

    private void txtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusLost
        
    }//GEN-LAST:event_txtPesquisarFocusLost

    private void txtPesquisarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMouseReleased
        
    }//GEN-LAST:event_txtPesquisarMouseReleased

    private void txtPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMousePressed
        
    }//GEN-LAST:event_txtPesquisarMousePressed

    private void txtPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMouseClicked
        
    }//GEN-LAST:event_txtPesquisarMouseClicked

    private void txtPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMouseExited
        if (txtPesquisar.getText().equals(""))
            txtPesquisar.setText("Pesquisar por...");
    }//GEN-LAST:event_txtPesquisarMouseExited

    private void txtPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarMouseEntered
        if (txtPesquisar.getText().equals("Pesquisar por..."))
            txtPesquisar.setText("");
    }//GEN-LAST:event_txtPesquisarMouseEntered

    public void limpar() {
        txtCodBarras.setText("");
        txtCodigo.setText("");
        txtData.setText("");
        txtDescricao.setText("");
        txtEstoque.setText("");
        txtEstoqueMax.setText("");
        txtEstoqueMin.setText("");
        txtFatorLucro.setText("");
        txtNcm.setText("");
        txtPrecoCompra.setText("");
        txtPrecoVenda.setText("");
        txtNome.setText("");   
        txtID.setText("");
        lblImagem.setIcon(null);
    }
    
    public void cadastrar() {
        count ++;
        conexao = Conexao.obterConexao();
        try {
            String sql = "INSERT INTO produto (cod, status, nome, descricao, "
                    + "qtd_estoque, estoque_minimo, estoque_maximo, "
                    + "preco_compra, preco_venda, bar_code, ncm, "
                    + "fator, data_cadastro, imagem) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            pst.setString(2, String.valueOf(cbStatus.getSelectedItem().toString().charAt(0)));
            pst.setString(3, txtNome.getText());
            pst.setString(4, txtDescricao.getText());
            pst.setString(5, txtEstoque.getText());
            pst.setString(6, txtEstoqueMin.getText());
            pst.setString(7, txtEstoqueMax.getText());
            pst.setString(8, txtPrecoCompra.getText());
            pst.setString(9, txtPrecoVenda.getText());
            pst.setString(10, txtCodBarras.getText());
            pst.setString(11, txtNcm.getText());          
            pst.setString(12, txtFatorLucro.getText());
            pst.setString(13, txtData.getText());
            pst.setString(14, "/imagens/" + count);    
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Registration successful");
            limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error registering");
            e.printStackTrace();
        }
        //limpar();
    }
    
    public void listar() {
        conexao = Conexao.obterConexao();
        DefaultTableModel model = (DefaultTableModel) tblProdutos.getModel();
        model.setNumRows(0);
        try {
            String sql = "SELECT cod, status, nome, qtd_estoque, "
                    + "estoque_minimo, estoque_maximo, preco_compra, "
                    + "preco_venda, fator FROM produto WHERE nome like ?";
            pst = conexao.prepareStatement(sql);
            
            if (txtPesquisar.getText().equals("Pesquisar por..."))
                pst.setString(1, "" + "%");
            else
                pst.setString(1, txtPesquisar.getText() + "%");
            
            rs = pst.executeQuery();
            while (rs.next()) {
                System.out.println(rs.getString("nome"));
                model.addRow(new Object[]{
                    rs.getString("cod"),
                    rs.getString("status"),
                    rs.getString("nome"),
                    rs.getInt("qtd_estoque"),
                    rs.getInt("estoque_minimo"),
                    rs.getInt("estoque_maximo"),
                    rs.getFloat("preco_compra"),
                    rs.getFloat("preco_venda"),
                    rs.getFloat("fator")
                });
            }
            pst.close();
        } catch (Exception e) {
            e.getStackTrace();
            System.out.println(e.getMessage());
        // fim catch
        }
        txtPesquisar.grabFocus();
    } // fim listar
    
    public void update() { 
        conexao = Conexao.obterConexao();
        try {
            String sql = "UPDATE produto SET cod=?, status=?, nome=?, descricao=?, "
                    + "qtd_estoque=?, estoque_minimo=?, estoque_maximo=?, "
                    + "preco_compra=?, preco_venda=?, bar_code=?, ncm=?, "
                    + "fator=?, data_cadastro=? WHERE cod = ?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            pst.setString(2, String.valueOf(cbStatus.getSelectedItem().toString().charAt(0)));
            pst.setString(3, txtNome.getText());
            pst.setString(4, txtDescricao.getText());
            pst.setString(5, txtEstoque.getText());
            pst.setString(6, txtEstoqueMin.getText());
            pst.setString(7, txtEstoqueMax.getText());
            pst.setString(8, txtPrecoCompra.getText());
            pst.setString(9, txtPrecoVenda.getText());
            pst.setString(10, txtCodBarras.getText());
            pst.setString(11, txtNcm.getText());
            pst.setString(12, txtFatorLucro.getText());
            pst.setString(13, txtData.getText());
            pst.setString(14, txtCodigo.getText());
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
            limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não atualizado!");
            System.out.println(e.getMessage());
        }
        //limpar();
        listar();
    } // end update
    
    public void excluir(String code) {
        conexao = Conexao.obterConexao();
        try {
            String url = "DELETE FROM produto WHERE cod=?";
            pst = conexao.prepareStatement(url);
            pst.setString(1, code);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
            limpar();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir!");         
            System.out.println(e.getMessage());
        }
        listar();
    }
    
    // pega todos os itens da linha selecionada da tabela
    public void selecionar() { 
        String var;
        var = (tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0).toString());
        try {
            conexao = Conexao.obterConexao();
            String sql = "SELECT ID, descricao, bar_code, ncm, data_cadastro, "
                    + "imagem, status, nome, qtd_estoque, estoque_minimo, "
                    + "estoque_maximo, preco_compra, preco_venda, fator, "
                    + "cod, imagem FROM produto WHERE cod = ?";
            pst = conexao.prepareStatement(sql);  
            pst.setInt(1, Integer.parseInt(var));
            rs = pst.executeQuery();

            if (rs.next()) {
                txtID.setText("ID = " + rs.getString("ID"));
                txtDescricao.setText(rs.getString("descricao"));
                txtCodBarras.setText(String.valueOf(rs.getLong("bar_code")));
                txtNcm.setText(rs.getString("ncm"));
                txtData.setText(rs.getString("data_cadastro"));
                lblImagem.setText(rs.getString("imagem"));
                cbStatus.setSelectedItem(rs.getString("status"));
                txtNome.setText(rs.getString("nome"));
                txtEstoque.setText(String.valueOf(rs.getLong("qtd_estoque")));
                txtEstoqueMin.setText(String.valueOf(rs.getLong("estoque_minimo")));
                txtEstoqueMax.setText(String.valueOf(rs.getLong("estoque_maximo")));
                txtPrecoCompra.setText(String.valueOf(rs.getFloat("preco_compra")));
                txtPrecoVenda.setText(String.valueOf(rs.getFloat("preco_venda")));
                txtFatorLucro.setText(String.valueOf(rs.getInt("fator")));
                txtCodigo.setText(String.valueOf(rs.getLong("cod")));
                
                String caminho = rs.getString("imagem");      
                URL imagePath = FrmCadastro.class.getResource(caminho + ".jpg");
                
                if (imagePath == null) {
                    imagePath = FrmCadastro.class.getResource(caminho + ".png");
                }
                if (imagePath == null) {
                    imagePath = FrmCadastro.class.getResource("/imagens/default.jpg");
                }
                         
                ImageIcon icon = new ImageIcon(imagePath);
                lblImagem.setIcon(icon);
                lblImagem.setText("");   
                
            } else {
                System.out.println("Nenhum registro encontrado.");
            }
            
        } catch (SQLException e) {
            e.printStackTrace(); // Para diagnosticar o problema
            System.out.println(e.getMessage());
        }
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtEstoqueMax;
    private javax.swing.JTextField txtEstoqueMin;
    private javax.swing.JLabel txtFatorLucro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNcm;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
