/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raizesdaterra;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author PEG
 */
public class FormaEntrega extends javax.swing.JFrame {
    private static FormaEntrega entrega;
    private ButtonGroup group = new ButtonGroup();
    
    /**
     * Creates new form MAIN
     */
    public FormaEntrega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIcon = new javax.swing.JLabel();
        jButton_main = new javax.swing.JButton();
        jButton_logar = new javax.swing.JButton();
        jButton_search = new javax.swing.JButton();
        jButton_messages = new javax.swing.JButton();
        jButton_cart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        backGround2 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIcon.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/userIcon.png"))); // NOI18N
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 70, -1, -1));

        jButton_main.setBackground(new java.awt.Color(255, 247, 221));
        jButton_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/logo.png"))); // NOI18N
        jButton_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mainActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        jButton_main.setBorderPainted(false);
        jButton_main.setFocusPainted(false);
        jButton_main.setContentAreaFilled(false);

        jButton_logar.setBackground(new java.awt.Color(255, 247, 221));
        jButton_logar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton_logar.setText("LOGAR");
        jButton_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 90, -1, -1));
        jButton_logar.setBorderPainted(false);
        jButton_logar.setFocusPainted(false);
        jButton_logar.setContentAreaFilled(false);

        jButton_search.setBackground(new java.awt.Color(255, 247, 221));
        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/searchIcon.png"))); // NOI18N
        getContentPane().add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));
        jButton_search.setBorderPainted(false);
        jButton_search.setFocusPainted(false);
        jButton_search.setContentAreaFilled(false);

        jButton_messages.setBackground(new java.awt.Color(255, 247, 221));
        jButton_messages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/messagesIcon.png"))); // NOI18N
        getContentPane().add(jButton_messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 80, 70, -1));
        jButton_messages.setBorderPainted(false);
        jButton_messages.setFocusPainted(false);
        jButton_messages.setContentAreaFilled(false);

        jButton_cart.setBackground(new java.awt.Color(255, 247, 221));
        jButton_cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/cartIcon.png"))); // NOI18N
        jButton_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cartActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1572, 80, 80, -1));
        jButton_cart.setBorderPainted(false);
        jButton_cart.setFocusPainted(false);
        jButton_cart.setContentAreaFilled(false);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, -1, -1));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1277, 876, 305, 60));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 833, 492, 64));

        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 758, -1, -1));

        jRadioButton2.setContentAreaFilled(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 375, -1, -1));

        jRadioButton3.setContentAreaFilled(false);
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 469, -1, -1));

        jRadioButton4.setContentAreaFilled(false);
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 564, -1, -1));

        jTextField1.setBackground(new java.awt.Color(249, 198, 126));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextField1.setText("Pesquisar no site");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 79, 470, 45));
        setjButton_logar(Inicio.getUser().getNome());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(249, 198, 126));
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jTextField2.setText("Dom Luiz, Rua das Espatódeas - N°114");
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, 390, 40));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(223, 158, 62));
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField3.setText("123.456.789-10");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 390, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(223, 158, 62));
        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField4.setText("(xx)xxxxx-xxxx");
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 240, 40));
        jTextField4.setText(Inicio.getUser().getCelularEmail());

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(223, 158, 62));
        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField5.setText("Pessoa Física");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 210, 40));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(223, 158, 62));
        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField6.setText("userName");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 360, 40));
        jTextField6.setText(Inicio.getUser().getNome());
        setjButton_logar(Inicio.getUser().getNome());
        agruparBotoes();

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(249, 198, 126));
        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setText("44,92");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 460, 110, 40));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(249, 198, 126));
        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField8.setText("29,44");
        jTextField8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 556, 110, 40));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(249, 198, 126));
        jTextField9.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField9.setText("21,44");
        jTextField9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 368, 110, 40));

        backGround2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/backgrounds/EntregaScreen.png"))); // NOI18N
        getContentPane().add(backGround2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1650, 730));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/backgrounds/Main.png"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logarActionPerformed
        if (getjButton_logar().equals("LOGAR")) {  
            Login logar = new Login();
            logar.setVisible(true);
            this.setEnabled(false);
        } else {
            MenuLogin.exibirMenu().setVisible(true);
        }
    }//GEN-LAST:event_jButton_logarActionPerformed

    private void jButton_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cartActionPerformed
        MenuLogin menu = new MenuLogin();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton_cartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mainActionPerformed
        Inicio.getInstance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_mainActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NovoEndereço.getInstance().setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!jRadioButton1.isSelected())
            JOptionPane.showMessageDialog(null, "Selecione um endereço!", "Erro!", 2);
        else if (!jRadioButton2.isSelected() && !jRadioButton3.isSelected() && !jRadioButton4.isSelected())
            JOptionPane.showMessageDialog(null, "Selecione a forma de entrega!", "Erro!", 2);
        else {
            Pagamento.getInstance().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public static FormaEntrega getInstance() {
        if (entrega == null)
            entrega = new FormaEntrega();
        return entrega;
    }
    
    private void agruparBotoes() {
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        group.add(jRadioButton4);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getInstance();
                entrega.setVisible(true);
            }
        });
    }

    public String getjButton_logar() {
        return jButton_logar.getText();
    }

    public void setjButton_logar(String user) {
        jButton_logar.setText(user);
    }

    public String getjTextField2() {
        return jTextField2.getText();
    }

    public void setjTextField2(String endereco) {
        jTextField2.setText(endereco);
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel backGround2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_cart;
    private javax.swing.JButton jButton_logar;
    private javax.swing.JButton jButton_main;
    private javax.swing.JButton jButton_messages;
    private javax.swing.JButton jButton_search;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
