/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raizesdaterra;

import javax.swing.JButton;
import javax.swing.JOptionPane;
/**
 *
 * @author PEG
 */
public class Inicio extends javax.swing.JFrame {
    private static Inicio inicio;
    
    /**
     * Creates new form MAIN
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIcon = new javax.swing.JLabel();
        jButton_main = new javax.swing.JButton();
        jButton_logar = new javax.swing.JButton();
        jButton_search = new javax.swing.JButton();
        jButton_messages = new javax.swing.JButton();
        jButton_cart = new javax.swing.JButton();
        jButton_product1 = new javax.swing.JButton();
        jButton_product2 = new javax.swing.JButton();
        jButton_product3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIcon.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/userIcon.png"))); // NOI18N
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 70, -1, -1));

        jButton_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/logo.png"))); // NOI18N
        getContentPane().add(jButton_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        jButton_main.setBorderPainted(false);
        jButton_main.setFocusPainted(false);
        jButton_main.setContentAreaFilled(false);

        jButton_logar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton_logar.setText("LOGAR");
        jButton_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 90, -1, -1));
        jButton_logar.setBorderPainted(false);
        jButton_logar.setFocusPainted(false);
        jButton_logar.setContentAreaFilled(false);

        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/searchIcon.png"))); // NOI18N
        getContentPane().add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));
        jButton_search.setBorderPainted(false);
        jButton_search.setFocusPainted(false);
        jButton_search.setContentAreaFilled(false);

        jButton_messages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/messagesIcon.png"))); // NOI18N
        getContentPane().add(jButton_messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 80, 70, -1));
        jButton_messages.setBorderPainted(false);
        jButton_messages.setFocusPainted(false);
        jButton_messages.setContentAreaFilled(false);

        jButton_cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/cartIcon.png"))); // NOI18N
        getContentPane().add(jButton_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1572, 80, 80, -1));
        jButton_cart.setBorderPainted(false);
        jButton_cart.setFocusPainted(false);
        jButton_cart.setContentAreaFilled(false);

        jButton_product1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/product1.png"))); // NOI18N
        getContentPane().add(jButton_product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));
        jButton_product1.setBorderPainted(false);
        jButton_product1.setFocusPainted(false);
        jButton_product1.setContentAreaFilled(false);

        jButton_product2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/product2.png"))); // NOI18N
        getContentPane().add(jButton_product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));
        jButton_product2.setBorderPainted(false);
        jButton_product2.setFocusPainted(false);
        jButton_product2.setContentAreaFilled(false);

        jButton_product3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/product3.png"))); // NOI18N
        getContentPane().add(jButton_product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 370, -1, -1));
        jButton_product3.setBorderPainted(false);
        jButton_product3.setFocusPainted(false);
        jButton_product3.setContentAreaFilled(false);

        jTextField1.setText("Procurar Produto");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 460, 40));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/MAIN.png"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logarActionPerformed
        // TODO add your handling code here:
        Logar logar = new Logar();
        logar.setVisible(true);
        inicio.setVisible(false);
    }//GEN-LAST:event_jButton_logarActionPerformed

    
    public static Inicio getInstance() {
        if (inicio == null)
            inicio = new Inicio();
        return inicio;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getInstance();
                inicio.setVisible(true);
            }
        });
    }

    public String getjButton_logar() {
        return jButton_logar.getText();
    }

    public void setjButton_logar(String user) {
        jButton_logar.setText(user);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton jButton_cart;
    private javax.swing.JButton jButton_logar;
    private javax.swing.JButton jButton_main;
    private javax.swing.JButton jButton_messages;
    private javax.swing.JButton jButton_product1;
    private javax.swing.JButton jButton_product2;
    private javax.swing.JButton jButton_product3;
    private javax.swing.JButton jButton_search;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
