/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raizesdaterra;

import javax.swing.JOptionPane;

/**
 *
 * @author PEG
 */
public class Logar extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Logar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_logar = new javax.swing.JButton();
        jCheckBox_conected = new javax.swing.JCheckBox();
        jTextField_user = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 480, 122, 36));
        jButton_logar.setBorderPainted(false);
        jButton_logar.setFocusPainted(false);
        jButton_logar.setContentAreaFilled(false);
        getContentPane().add(jCheckBox_conected, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 434, 20, 18));
        jCheckBox_conected.setBorderPainted(false);
        jCheckBox_conected.setFocusPainted(false);
        jCheckBox_conected.setContentAreaFilled(false);

        jTextField_user.setBackground(new java.awt.Color(223, 158, 62));
        jTextField_user.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 241, 581, 37));
        jTextField_user.setOpaque(true);

        jTextField_password.setBackground(new java.awt.Color(223, 158, 62));
        jTextField_password.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jTextField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 373, 581, 37));
        jTextField_user.setOpaque(true);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/LoginScreen.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logarActionPerformed
        // TODO add your handling code here:
        String password = jTextField_password.getText();
        if (!"1234".equals(password))
            JOptionPane.showMessageDialog(null, "Senha inválida!", "Erro!", 0);
        else {            
            String user = jTextField_user.getText();
            Inicio.getInstance().setjButton_logar(user);
            Inicio.getInstance().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_logarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton_logar;
    private javax.swing.JCheckBox jCheckBox_conected;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables
}
