/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raizesdaterra;

import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author PEG
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_logar = new javax.swing.JButton();
        jCheckBox_conected = new javax.swing.JCheckBox();
        jTextField_user = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_logar.setContentAreaFilled(false);
        jButton_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 480, 122, 36));
        jButton_logar.setBorderPainted(false);
        jButton_logar.setFocusPainted(false);
        jButton_logar.setContentAreaFilled(false);

        jCheckBox_conected.setBackground(new java.awt.Color(223, 158, 62));
        jCheckBox_conected.setContentAreaFilled(false);
        getContentPane().add(jCheckBox_conected, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 434, 20, 18));
        jCheckBox_conected.setBorderPainted(false);
        jCheckBox_conected.setFocusPainted(false);
        jCheckBox_conected.setContentAreaFilled(false);

        jTextField_user.setBackground(new java.awt.Color(223, 158, 62));
        jTextField_user.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_userActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 241, 581, 37));
        jTextField_user.setOpaque(true);

        jTextField_password.setBackground(new java.awt.Color(223, 158, 62));
        jTextField_password.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jTextField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 373, 581, 37));
        jTextField_user.setOpaque(true);

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 230, 30));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setContentAreaFilled(false);

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 280, 30));
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setContentAreaFilled(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/backgrounds/LoginScreen.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logarActionPerformed
        try {           
            if (!jTextField_user.getText().equals(Inicio.getUser().getNome()))
                JOptionPane.showMessageDialog(null, "Usuário inválido!", "Erro!", 0);
            else if (!jTextField_password.getText().equals(Inicio.getUser().getSenha()))
                JOptionPane.showMessageDialog(null, "Senha inválida!", "Erro!", 0);
            else {
                Inicio.getInstance().setjButton_logar(Inicio.getUser().getNome());
                Inicio.getInstance().setEnabled(true);
                this.dispose();
            }
        } catch (Exception e) {
            if (jTextField_user.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Informe um usuário!", "Dados inválidos!", 2);
            else if (jTextField_password.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Informe uma senha!", "Dados inválidos!", 2);
            else
                JOptionPane.showMessageDialog(null, "Crie uma conta!", "Usuário não existe!", 0);
        }
    }//GEN-LAST:event_jButton_logarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cadastrar cadastro = new Cadastrar();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EsqueciSenha fSenha = new EsqueciSenha();
        fSenha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_userActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_logar;
    private javax.swing.JCheckBox jCheckBox_conected;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables
}
