/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raizesdaterra;

import javax.swing.SwingConstants;

/**
 *
 * @author PEG
 */
public class MenuLogin extends javax.swing.JFrame {
    private static MenuLogin menu;
    
    /**
     * Creates new form MenuLogin
     */
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 247, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/myAccountIcon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 56, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/myBuysIcon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/myFavoritesIcon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 193, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raizesdaterra/imagens/logoutIcon.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 260, 53, 55));

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton1.setText("Sair");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 270, 160, -1));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setContentAreaFilled(false);

        jButton1.setHorizontalAlignment(SwingConstants.LEFT);

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton5.setText("Minha Conta");
        jButton5.setContentAreaFilled(false);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 20, 160, -1));
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.setContentAreaFilled(false);

        jButton5.setHorizontalAlignment(SwingConstants.LEFT);

        jButton6.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton6.setText("Vendas");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 145, 160, -1));
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setContentAreaFilled(false);

        jButton6.setHorizontalAlignment(SwingConstants.LEFT);

        jButton7.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton7.setText("Favoritos");
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 205, 160, -1));
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        jButton7.setContentAreaFilled(false);

        jButton7.setHorizontalAlignment(SwingConstants.LEFT);

        jButton8.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton8.setText("Compras");
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 80, 160, -1));
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setContentAreaFilled(false);

        jButton6.setHorizontalAlignment(SwingConstants.LEFT);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 330));

        setBounds(1280, 130, 240, 331);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    // Método que direciona para a tela Meus Pedidos
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        InfoPedido.getInstance().dispose();
        Rastreio.getInstance().dispose();
        this.dispose();
        
        MinhasVendas.getInstance().setVisible(true);
        MinhasVendas.getInstance().getjButton3().setEnabled(true);
        MinhasVendas.getInstance().setjButton3("Cadastrar novo produto");
        MinhasVendas.getInstance().getjButton2().setEnabled(false);
        Inicio.getInstance().setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    // Método que fecha todas as janelas e volta para o Inicio
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InfoPedido.getInstance().dispose();               
        MeusPedidos.getInstance().dispose();
        Rastreio.getInstance().dispose();
        this.dispose();
        
        Inicio.getInstance().setjButton_logar("LOGAR");
        Inicio.getInstance().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        InfoPedido.getInstance().dispose();
        Rastreio.getInstance().dispose();
        this.dispose();
        
        MinhasVendas.getInstance().setVisible(true);
        MinhasVendas.getInstance().getjButton3().setEnabled(false);
        MinhasVendas.getInstance().setjButton3("");
        MinhasVendas.getInstance().getjButton2().setEnabled(true);
        Inicio.getInstance().setVisible(false);       
    }//GEN-LAST:event_jButton8ActionPerformed

    public static MenuLogin exibirMenu() {
        if (menu == null)
            menu = new MenuLogin();
        return menu;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
